"""ASGI facade that serves the converter UI and constrains docling-serve.

The facade keeps Docling's official async file endpoints intact. It blocks
network-source routes before they reach docling-serve, performs cheap upload
boundary checks without retaining files, and applies no-store to dynamic
responses. The conversion contract remains generated by docling-serve itself.
"""

from __future__ import annotations

import re
from pathlib import Path, PurePosixPath
from typing import Awaitable, Callable

from fastapi import FastAPI
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

MAX_FILE_BYTES = 25 * 1024 * 1024
MAX_FILES = 5
STATIC_DIR = Path(__file__).parent / "static"
UPLOAD_PATH = "/v1/convert/file/async"
ALLOWED_EXTENSIONS = {
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    ".odt", ".ods", ".odp", ".epub", ".pages", ".html", ".htm",
    ".md", ".markdown", ".adoc", ".asciidoc", ".tex", ".latex",
    ".csv", ".tsv", ".png", ".jpg", ".jpeg", ".tif", ".tiff",
    ".bmp", ".webp", ".eml", ".msg", ".vtt", ".boxnote", ".json",
    ".dclg", ".dclx", ".xml", ".xbrl", ".jats",
}


def _safe_filename(filename: str) -> bool:
    """Reject path components, controls and names that cannot safely round-trip."""
    if not filename or len(filename) > 200 or any(ord(char) < 32 for char in filename):
        return False
    normalized = filename.replace("\\", "/")
    return PurePosixPath(normalized).name == filename and ".." not in filename


def _signature_matches(extension: str, data: bytes) -> bool:
    """Validate signatures only for formats with stable, useful magic bytes."""
    signatures = {
        ".pdf": (b"%PDF-",),
        ".png": (b"\x89PNG\r\n\x1a\n",),
        ".jpg": (b"\xff\xd8\xff",),
        ".jpeg": (b"\xff\xd8\xff",),
        ".gif": (b"GIF87a", b"GIF89a"),
        ".tif": (b"II*\x00", b"MM\x00*"),
        ".tiff": (b"II*\x00", b"MM\x00*"),
        ".bmp": (b"BM",),
        ".webp": (b"RIFF",),
        ".doc": (b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1",),
        ".xls": (b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1",),
        ".ppt": (b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1",),
        ".msg": (b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1",),
    }
    zip_extensions = {".docx", ".xlsx", ".pptx", ".odt", ".ods", ".odp", ".epub", ".pages", ".dclx"}
    if extension in zip_extensions:
        return data.startswith(b"PK\x03\x04")
    if extension == ".webp":
        return data.startswith(b"RIFF") and data[8:12] == b"WEBP"
    expected = signatures.get(extension)
    return expected is None or any(data.startswith(value) for value in expected)


def _parse_multipart_files(content_type: str, body: bytes) -> list[tuple[str, bytes]]:
    """Read multipart file parts for guardrails, never storing or logging them."""
    match = re.search(r"boundary=([^;]+)", content_type, re.IGNORECASE)
    if not match:
        raise ValueError("missing multipart boundary")
    boundary = match.group(1).strip().strip('"').encode("ascii", "strict")
    chunks = body.split(b"--" + boundary)
    files: list[tuple[str, bytes]] = []
    for chunk in chunks[1:-1]:
        if chunk.startswith(b"\r\n"):
            chunk = chunk[2:]
        header, separator, data = chunk.partition(b"\r\n\r\n")
        if not separator:
            continue
        disposition = re.search(rb'filename="([^"\r\n]+)"', header, re.IGNORECASE)
        if not disposition:
            continue
        filename = disposition.group(1).decode("utf-8", "strict")
        files.append((filename, data[:-2] if data.endswith(b"\r\n") else data))
    return files


def _validate_upload(content_type: str, body: bytes) -> str | None:
    if len(body) > MAX_FILE_BYTES * MAX_FILES + 256 * 1024:
        return "Upload exceeds the batch size limit."
    try:
        files = _parse_multipart_files(content_type, body)
    except (UnicodeDecodeError, ValueError):
        return "Malformed upload."
    if not 1 <= len(files) <= MAX_FILES:
        return "Upload one to five files."
    for filename, data in files:
        extension = PurePosixPath(filename.lower()).suffix
        if not _safe_filename(filename) or extension not in ALLOWED_EXTENSIONS:
            return "An uploaded file type is not allowed."
        if not data or len(data) > MAX_FILE_BYTES or not _signature_matches(extension, data[:16]):
            return "An uploaded file failed safety validation."
    return None


class PrivacyBoundary:
    """ASGI middleware that blocks remote sources and validates upload envelopes."""

    def __init__(self, app: Callable[..., Awaitable[None]]) -> None:
        self.app = app

    async def __call__(self, scope, receive, send) -> None:  # type: ignore[no-untyped-def]
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return
        path = scope["path"]
        blocked_source = path.startswith("/v1/convert/source") or (
            path.startswith("/v1/chunk/") and path.endswith("/source")
        )
        if blocked_source:
            response = JSONResponse({"detail": "Remote-source conversion is disabled."}, status_code=404)
            await response(scope, receive, send)
            return
        headers = {key.decode().lower(): value.decode() for key, value in scope["headers"]}
        messages = []
        if scope["method"] == "POST" and path == UPLOAD_PATH:
            body = b""
            while True:
                message = await receive()
                messages.append(message)
                body += message.get("body", b"")
                if len(body) > MAX_FILE_BYTES * MAX_FILES + 256 * 1024:
                    response = JSONResponse({"detail": "Upload exceeds the batch size limit."}, status_code=422)
                    await response(scope, receive, send)
                    return
                if not message.get("more_body", False):
                    break
            error = _validate_upload(headers.get("content-type", ""), body)
            if error:
                response = JSONResponse({"detail": error}, status_code=422)
                await response(scope, receive, send)
                return
        index = 0

        async def replay_receive():
            nonlocal index
            if messages:
                message = messages[index]
                index += 1
                return message
            return await receive()

        async def no_store_send(message):
            if message["type"] == "http.response.start" and not path.startswith("/assets/"):
                headers_out = list(message.get("headers", []))
                headers_out.append((b"cache-control", b"no-store"))
                message["headers"] = headers_out
            await send(message)

        await self.app(scope, replay_receive, no_store_send)


def _hide_remote_routes(app: FastAPI) -> None:
    """Keep OpenAPI aligned with the externally reachable privacy boundary."""
    original_openapi = app.openapi

    def filtered_openapi():
        schema = original_openapi()
        schema["paths"] = {
            path: operations
            for path, operations in schema["paths"].items()
            if not path.startswith("/v1/convert/source") and "/source" not in path
        }
        return schema

    app.openapi = filtered_openapi  # type: ignore[method-assign]


def create_app() -> FastAPI:
    from docling_serve.app import create_app as create_docling_app

    app = create_docling_app()
    _hide_remote_routes(app)
    app.mount("/assets", StaticFiles(directory=str(STATIC_DIR)), name="converter-assets")

    @app.get("/", include_in_schema=False)
    async def converter_index():
        return FileResponse(STATIC_DIR / "index.html", headers={"Cache-Control": "no-store"})

    return app


app = PrivacyBoundary(create_app())
